### ISSUE TITLE
Landing Page for Next.js application

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#13]
# Overview

We need to develop a new landing page for our website. This homepage will serve as the main entry point for users and should be both visually appealing and functional. The key feature of this landing page will be a tab called "Versify," which will redirect users to our Bible verse similarity finder. A dark mode + tech theme is preferred, but we are open to making multiple designs to see which is best.

# Tasks

- **Design Wireframe for Landing Page**
  - Create a wireframe for the homepage, focusing on user experience and visual appeal.
  - Include the "Versify" tab in the routing so that it can route to the Bible verse finder.

- **Develop Styling for Homepage**
  - Code the landing page using JavaScript and either Tailwind CSS or Material UI.
  - Ensure the page is responsive and works well on both desktop and mobile devices.

- **Implement "Versify" Tab**
  - Develop the "Versify" tab that redirects to the Bible verse similarity finder.
  - Ensure the redirection is seamless and intuitive for users.

**Comment by JustinhSE** [comment]
We have installed magic ui as well to make designing components easier!

**Comment by d-beloved** [comment]
@JustinhSE I would like to take this up, thanks.

**Comment by d-beloved** [comment]
@JustinhSE and @Namit2111 do we want the light and dark theme to work across the whole app or just on the landing page? I think it's supposed to be the whole app, but I want to run it by you first.

**Comment by JustinhSE** [comment]
@d-beloved whole app but we can worry abt dark mode in future iterations

**Comment by JustinhSE** [comment]
Thanks for asking but don't wanna put to much work in one PR, want you to get all 4!

**Comment by d-beloved** [comment]
😄 Okay. The landing page design we agreed on looks like a dark mode though. I will skip the light and dark modes for now, and we can open a new issue. I was asking because it would mean I would need to touch the Versify page styles, but as you said, let's leave the work for themes for another PR.

_P.S. even though Hacktoberfest made me discover this project, I intend to keep working on this beyond October._

**Comment by JustinhSE** [comment]
@d-beloved I understand, honestly save it for another issue and just keep the versify style currently. We can just open another issue as you said to make the versify page have a dark mode since its design is pretty simplistic. Also thanks so much, I'm happy you love this project!
