### ISSUE TITLE
Add new PR template

### ISSUE THREAD

**Issue by Laikokwui** [Namit2111/bible-verse-finder#15]

**Comment by Namit2111** [comment]
Before creating a PR, discuss your approach here or  on discord first.

**Comment by Laikokwui** [comment]
Down below is the template I come out with. @Namit2111 let me know anything you want me to add.

1. Description
2. Related Issues
3. Changes List
4. Type of Changes
- [ ] > Bug fixes (existing bugs and issues)
- [ ] > enhancement (improve or change approach for existing features)
- [ ] > breaking changes (new changes that will cause existing feature to break)
- [ ] > documentations
5. Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ]  My changes generate no new warnings
- [ ]  New and existing unit tests pass locally with my changes
- [ ]  Any dependent changes have been merged and published in downstream modules

**Comment by JustinhSE** [comment]
@Namit2111 @Laikokwui When i open an issue, the template doesn't show up? I removed it and renamed it to be lower case according to the github doc and it still doesn't show up when I click new issue? Is their a way to resolve this?

**Comment by Laikokwui** [comment]
@JustinhSE the one I created is for pr template only. If you need issues template you need to create an issue_template file

**Comment by JustinhSE** [comment]
@Laikokwui wow.... I don't know how I missed that, thanks 😅😅😅
