### ISSUE TITLE
v2 Bible Verse Finder - HTML -> Next.js

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#2]
## Overview
Our current framework is good, but we want to take this to the next level. Using something like Next.js will help us route and scale this project easier. We want to have a new UX and upgraded visual, multiple pages (home page and bible verse similarity), and it should be written in TypeScript (preferred) or JavaScript.

## Tasks
- Implement multiple pages: home page and bible verse similarity.
- Integrate the bible-app directory and the additional files such as the [app.py](https://github.com/Namit2111/bible-verse-finder/blob/main/app.py) and the `index.html` file so that we can upgrade our tech stack. 
- Onrender should still be able to render your changes [deployed version](https://bible-verse-finder-1.onrender.com/)

**Comment by Namit2111** [comment]
Hey! Using anyting like Nextjs or any other framework will not impact our ML model in any way , we can freely use any framework in the frontend

**Comment by JustinhSE** [comment]
You are on it!!! I was just setting this up for anyone who wanted to join.

**Comment by JustinhSE** [comment]
Thanks for letting me know @Namit2111 , if we wanted too, would anything change? I just don't want to interfere with the calls within the HTML file `index.html`

**Comment by Namit2111** [comment]
No! Nothing will change

**Comment by JustinhSE** [comment]
Alright let me change the issue!

**Comment by JustinhSE** [comment]
something cool - https://magicui.design/docs/components/rainbow-button

**Comment by JustinhSE** [comment]
- I created the next.js + magicUI into it,we just need to integrate the 2

**Comment by JustinhSE** [comment]
If you have any questions about this issue please comment them here!

**Comment by rajatkriplani** [comment]
Hey @JustinhSE as mentioned on Discord there are a few steps to migrate from html to next.js so can you break this issue in parts (divide and conquer)? so that it becomes easy to keep track of the progress and resolve one issue at a time.

**Comment by d-beloved** [comment]
This is looking interesting. In addition to @rajatkriplani's suggestion, @JustinhSE, do you have a design in mind for ```the home page and bible verse similarity``` , maybe a mockup? That will help with understanding the scope much better.

**Comment by JustinhSE** [comment]
@d-beloved honestly, migration is most important at this point. Although a good looking UX at the end of this issue would be amazing, I am more concerned about the backend aspect of this right now. You can reference our deployed version in our `readme.md`, it doesn't have to look any better than that when we link it. 


The most important thing is just integrating the 2 so that input and output work accordingly

**Comment by JustinhSE** [comment]
So home for example could literally be text of home. But the Bible verse similarity tab in next.js would need the functionality our current one does

**Comment by JustinhSE** [comment]
> Hey @JustinhSE as mentioned on Discord there are a few steps to migrate from html to next.js so can you break this issue in parts (divide and conquer)? so that it becomes easy to keep track of the progress and resolve one issue at a time.

@rajatkriplani yes but to break this issue down into smaller ones, I would need to know the tasks you would like to do so I can plan accordingly

**Comment by rajatkriplani** [comment]
> > Hey @JustinhSE as mentioned on Discord there are a few steps to migrate from html to next.js so can you break this issue in parts (divide and conquer)? so that it becomes easy to keep track of the progress and resolve one issue at a time.
> 
> @rajatkriplani yes but to break this issue down into smaller ones, I would need to know the tasks you would like to do so I can plan accordingly

Below are the step to migrate, and please let me know if I'm missing anything:

### Backend
- Keep flask backend or switch to next.js API?
- Change`app.py` to return JSON

### Frontend
- Convert `index.html` to Next.js
- `similarity.txt` use `fetch` to call Flask or Next.js API
- Update `page.tsx`

### Deployment
- Well this depends upon Flask or Next.js


I can start with updating page.tsx and build it using:
- `utils.ts` (`cn` function)
- `globals.css` which contains Tailwind's base
- `layout.tsx` for structure and global elements.

**Comment by d-beloved** [comment]
These steps seems solid to me @rajatkriplani, I am available for the
frontend aspect of things (converting index.html to Next.js) if it'll be an
handful for you. cc: @JustinfhSE

**Comment by JustinhSE** [comment]
@rajatkriplani the steps look great! @d-beloved you can also work on this issue, but you both will have to coordinate tasks.

**Comment by JustinhSE** [comment]
Pinging @Namit2111 for the deployment steps however to make sure these changes do not cause side effects

**Comment by rajatkriplani** [comment]
> @rajatkriplani the steps look great! @d-beloved you can also work on this issue, but you both will have to coordinate tasks.

okay, I'll start with page.tsx and will get in touch with @d-beloved to keep him updated.

**Comment by Namit2111** [comment]
Hi! @rajatkriplani 
we want to make an API in flask that will return a json object with results and user input this already implemented in app.py but currently it is serving index.html . We want to make an api of it.

For frontend we want similar ui that is copy the design of Index.html in nextjs , in nextjs use the flask app for completion of the app.

Your steps seems to align with what we want , so go ahead and let us know for any issue.

**Comment by rajatkriplani** [comment]
> Hi! @rajatkriplani we want to make an API in flask that will return a json object with results and user input this already implemented in app.py but currently it is serving index.html . We want to make an api of it.
> 
> For frontend we want similar ui that is copy the design of Index.html in nextjs , in nextjs use the flask app for completion of the app.
> 
> Your steps seems to align with what we want , so go ahead and let us know for any issue.

I'm updating `page.tsx` and @d-beloved will be working to convert `index.html` to next.js

**Comment by Namit2111** [comment]
Can you provide a timeline @rajatkriplani and @d-beloved

**Comment by rajatkriplani** [comment]
> Can you provide a timeline @rajatkriplani and @d-beloved

anything between 1 to 2 hours. And @d-beloved please drop you discord.

**Comment by rajatkriplani** [comment]
@Namit2111 I created a PR to update `page.tsx` but I'm not aware if @d-beloved is working on index.html as I was unable to make any contact.

**Comment by d-beloved** [comment]
Hey @rajatkriplani, I am not on my system at the moment. I'm at Church. You
can pick  it up if you're able to work on it now. I'll check back later
today to know the status.

**Comment by d-beloved** [comment]
> > Can you provide a timeline @rajatkriplani and @d-beloved
> 
> anything between 1 to 2 hours. And @d-beloved please drop you discord.

@rajatkriplani I have messaged you on the project thread on Discord
