### ISSUE TITLE
Add "Copy Verse to Clipboard" Functionality

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#20]
## Overview

We would like to enhance the user experience by adding a "Copy Verse to Clipboard" feature next to each verse displayed after a search query. This feature will allow users to easily copy a specific verse for reference or sharing purposes.

The functionality should be intuitive and seamlessly integrate with the existing user interface, ensuring that the process of copying a verse is straightforward and efficient.

For implementation reference, please review the example provided here: [Copy to Clipboard Component](https://ui.lukacho.com/components/copy-to-clipboard).

### Task

1. **Design Integration**: 
   - Implement a "Copy Verse to Clipboard" button/icon next to each verse in the search results.

2. **Functionality**:
   - Utilize the [Copy to Clipboard Component](https://ui.lukacho.com/components/copy-to-clipboard) as a guide to develop the feature.
   - Ensure the button copies the correct verse text to the clipboard upon user interaction.

3. **Testing**:
   - Conduct testing to verify that the clipboard functionality works across all supported browsers and devices.

**Comment by ByteJoseph** [comment]
At first, I thought this app was using Flask. Will it be migrated to Next.js

**Comment by JustinhSE** [comment]
@ByteJoseph yes it is integrated!

**Comment by JustinhSE** [comment]
@ByteJoseph would you like to take this issue?

**Comment by Namit2111** [comment]
Hi! @ByteJoseph this app uses Nextjs for frontend and flask for backend
