### ISSUE TITLE
Enhance User Experience with Animated Text Effects

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#21]
## Overview
As part of our ongoing effort to improve the user experience, we aim to implement smooth and visually appealing text effects for search results. By utilizing animation techniques, we can make the interface more engaging and intuitive. This enhancement will **only** be activated if search results are present, ensuring a cleaner and more efficient display of information.

### Task
1. **Research and Select Text Effects**  
   - Refer to [Motion Primitives Text Effect Documentation](https://motion-primitives.com/docs/text-effect) or [Motion Primitives Animated Group](https://motion-primitives.com/docs/animated-group) or [MagicUI's Blur In](https://magicui.design/docs/components/blur-in) to explore available text effects.

   - Evaluate which effects can seamlessly integrate with our current UI design for optimal performance and aesthetics.

2. **Implement Animated Text Effects**  
   - Use the selected text effects to animate search result bullet points.
   - Ensure the animations provide a smooth transition that enhances readability and user engagement.

4. **Testing and Optimization**  
   - Conduct thorough testing to ensure the animations work correctly across different devices and browsers.

**Comment by PiyushSinghjnp** [comment]
Please assign it to me @JustinhSE  as i have good exp in UI enhancement

**Comment by JustinhSE** [comment]
@PiyushSinghjnp can you explain your approach first for this?

**Comment by PiyushSinghjnp** [comment]
@JustinhSE 

**Research Effects:**
1. Explore Libraries: Check Motion Primitives or MagicUI for suitable animations like fade-in, slide-in, etc.
2. Evaluate Fit: Choose effects that blend with the UI and ensure performance efficiency.

**Integrate Effects:**
1. Apply to Results: Animate search result items with the selected effects when results are displayed.
2. Use CSS/JS: Implement using CSS @keyframes or JavaScript-based methods.

**Comment by JustinhSE** [comment]
Thanks so much! That looks correct! Try to mostly use JS to do this. @PiyushSinghjnp

**Comment by PiyushSinghjnp** [comment]
@JustinhSE ok

**Comment by JustinhSE** [comment]
@PiyushSinghjnp any updates?
