### ISSUE TITLE
Replace "Find Similar Verses" Button for Improved UX

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#22]
## Overview
The current "Find Similar Verses" button on the platform needs an update to enhance user experience. We propose replacing it with a Button, which is more visually appealing and aligns with modern design standards. This change should maintain the current functionality of running the similarity script when clicked.

To achieve this, we will utilize the Rainbow Button component as outlined in the Magic UI documentation: [Rainbow Button Documentation](https://magicui.design/docs/components/rainbow-button).

## Task
1. **Review Documentation**: Familiarize yourself with the Rainbow Button specifications and implementation guidelines from the Magic UI documentation.

2. **Design Integration**: 
   - Assess the current layout and design where the "Find Similar Verses" button is located.
   - Plan how to integrate the Rainbow Button seamlessly into the existing UI.

3. **Implement Button Replacement**:
   - Replace the existing button with the Rainbow Button component.
   - Ensure that the new button triggers the same similarity script upon being clicked, maintaining the existing functionality.

4. **Testing**:
   - Conduct thorough testing to ensure the new button operates as expected and the user experience is improved.
   - Verify that the button functions correctly across different browsers and devices.

**Comment by rairohit17** [comment]
Hey @JustinhSE  I ’m contributing to Hacktoberfest and would love to work on updating the "Find Similar Verses" button as per the proposal. I’ll replace the current button with the Rainbow Button from the Magic UI documentation while maintaining the same functionality of triggering the similarity script.

Could you please assign this issue to me? Looking forward to contributing!

**Comment by JustinhSE** [comment]
@rairohit17 thanks for the approach! You are now assigned
