### ISSUE TITLE
Add Tech Stack Section to About Us Page

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#24]
## Overview

We need to enhance our About Us page by including a dedicated section that showcases the tech stack used in our current project. This will help visitors and potential collaborators understand the technologies that power our application. 

### Task

1. **Review Project**: Go through our current project to identify all the technologies we are actively using. This includes programming languages, frameworks, libraries, tools, and any other relevant technologies.

2. **Curate List**: Create a concise and accurate list of these technologies. Ensure that only the technologies currently in use are included, removing any unused technologies.

3. **Design Section**: Based on the curated list, design a visually appealing section for the About Us page that highlights these technologies. Use the [Icon Cloud](https://magicui.design/docs/components/icon-cloud) to create engaging visuals.

4. **Implement Changes**: Update the About Us page to include the new tech stack section. Ensure that the section is responsive and maintains the overall design aesthetics of the page.

**Comment by JustAdi10** [comment]
Could you assign this to me

**Comment by JustinhSE** [comment]
@JustAdi10 do you mind discussing your approach quickly?

**Comment by JustinhSE** [comment]
sorry wrong commit # lol

**Comment by anjali-vaish** [comment]
@JustinhSE Hi,  I'd like to work on this. Could you please assign it to me. Thanks!

**Comment by Namit2111** [comment]
hi @anjali-vaish please use discord to describe your approach and design choices first

**Comment by maiHydrogen** [comment]
Hi @JustinhSE 
i think i can try to help on this one. here is my approach and please correct me if i'm wrong-
step 1. listing the used tech stack i.e. 
Backend: Flask (Python)
Frontend: HTML, CSS, JavaScript
Machine Learning: Python libraries such as scikit-learn (according to contribute doc in this repo, i'll try to find more like SQLAlchemy for database interactions,etc if any)  
step 2. filtering unused tech stack 
step 3. adding an About page in project
step 4. adding icon visuals using iconcloud and iconslugs from magicui and using css and adding some more visual effects like hovering or something else using magicui or javascript
can i work on this one ??

**Comment by Namit2111** [comment]
Hi @maiHydrogen you can work on it but before making any PR in future related to this get your design reviewed by @JustinhSE

**Comment by maiHydrogen** [comment]
@Namit2111 thanks for this
one question how can i get my design checked before making any PR because he will review my work only after he sees my PR isn't it?? please don't mind as i'm new to this opensource thing.

**Comment by JustinhSE** [comment]
@maiHydrogen when you run it on your local host, you can send a photo of what it looks like. And yes you would have to create an about us page. If you are uncomfortable doing that, I can just create a blank page for you if you want. Let me know

**Comment by maiHydrogen** [comment]
@JustinhSE thanks for clarifying 
Firstly I'll try to do that all by myself and if I feel I'm unable to do something I think I can let you know here afterall we are all here learn new things isn't it???

**Comment by JustinhSE** [comment]
@maiHydrogen true! Great to see you pushing out of your comfort zone

**Comment by JustinhSE** [comment]
@maiHydrogen and @d-beloved please communicate on the About us page, you have related issues now so make sure you are in communication regarding the build of this page

**Comment by maiHydrogen** [comment]
Sure Sir

**Comment by JustinhSE** [comment]
@maiHydrogen any updates?

**Comment by maiHydrogen** [comment]
@JustinhSE i have talked with d-beloved and we agreed upon building the page togather after discussing some designs and he will do his part first and then he will help me out meanwhile i have listed all the techstack used in this project via dependencies and all but i'm still figuring out how to filter them out. these are the ones what i have found -
Backend
Frameworks - Flask (Python)
Python Libraries - blinker,click,colorama,Flask,itsdangerous,Jinja2,joblib,MarkupSafe,nltk,numpy,regex,scikit-learn,scipy,threadpoolctl,tqdm,Werkzeug ,python-dotenv,pymongo,langchain_community,langchain_google_genai,fitz,qdrant,groq
Frontend
Languages & Frameworks - HTML,CSS,JavaScript,TypeScript,React,Next.js (next)
Libraries & Tools - react-dom,tailwindcss,postcss,lucide, react,clsx,radix ui,eslint,eslint-config-next
Utilities - json,NextResponse 
please correct me if i'm wrong anywhere

**Comment by JustinhSE** [comment]
Thanks for the update. That’s mostly what we used. But now consolidate that down into images that the tech cloud component supports @maiHydrogen

**Comment by JustinhSE** [comment]
@maiHydrogen any updates? Only a few days left for this issue

**Comment by maiHydrogen** [comment]
@JustinhSE sorry for this delay on this issue,i have seen the PR raised by d-beloved as i was waiting for that and i'm working on mine too.. i hope i'll raise the PR by this time tomorrow. thanks for the patience

**Comment by JustinhSE** [comment]
@maiHydrogen thanks for your response, just make sure its in accordance with his pr code wise

**Comment by maiHydrogen** [comment]
alright!

**Comment by JustinhSE** [comment]
@maiHydrogen it has been merged

**Comment by maiHydrogen** [comment]
@JustinhSE check if this works -
![Screenshot 2024-10-29 211157](https://github.com/user-attachments/assets/dc77cc16-07b7-46c1-8fac-cb991fd5c762)
on small screens it looks pretty good - 
![Screenshot 2024-10-29 201127](https://github.com/user-attachments/assets/2d035bc8-2ae6-49e3-a47e-df88c3c0e86e)
![Screenshot 2024-10-29 201154](https://github.com/user-attachments/assets/1b80071d-96a2-4643-9567-c37da1d5fe00)
however on big screens there are some issues with sizes of these divs with resizing windows and there are some icons which are unavailable in icon cloud

**Comment by JustinhSE** [comment]
Are you able to have a transparent background instead of white? @maiHydrogen

**Comment by maiHydrogen** [comment]
> Are you able to have a transparent background instead of white? @maiHydrogen

yes i am but some icons have black/dark shade so they will not be visible properly
here are some screenshots with transparent,black and a lighter shade of black background just tell me what you like
![Screenshot 2024-10-29 211811](https://github.com/user-attachments/assets/6d01ec37-7e64-47c1-8803-3288764c80d5)
![Screenshot 2024-10-29 212110](https://github.com/user-attachments/assets/85e8ce14-7b20-4e8a-9500-90004b4bc6dc)
![Screenshot 2024-10-29 212301](https://github.com/user-attachments/assets/10e5a4a1-d2d6-46ec-b482-535c283665dc)
erly

**Comment by d-beloved** [comment]
@maiHydrogen try to make the white background transparent...something like `bg-white/30`, try varying the degree of transparency to see how the icons with black outlines look.

**Comment by maiHydrogen** [comment]
> @maiHydrogen try to make the white background transparent...something like `bg-white/30`, try varying the degree of transparency to see how the icons with black outlines look.

i think instead of going into darker shade of white we should go with lighter shade of black as it will go along with the theme of page otherwise it will be too bright colours due to background gradient

**Comment by maiHydrogen** [comment]
![Screenshot 2024-10-29 215925](https://github.com/user-attachments/assets/b92ccf87-6bb5-4ce5-afa4-ab8c881bda38)
![Screenshot 2024-10-29 220800 - Copy](https://github.com/user-attachments/assets/07e9d9f1-0927-4e2c-bd7a-35b13a744ad1)
which one will be better?

**Comment by JustinhSE** [comment]
2
