### ISSUE TITLE
Backend - User Authentication

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#3]
🌟 Overview:
We're diving into the world of HTML and Python and want to add a user authentication process. We're looking to enable users to sign in using their email, Google, or GitHub accounts so we can add in some personalized features using their unique user IDs.

🚀 Task:
- Integrate logins via email, Google, or GitHub so we can add more personalization to our platform!

(This issue is to find logins using HTML until #2 is done)

**Comment by unclebinary1001** [comment]
I would like to clarify which User Authentication service is planned to be used. I am aware that Clerk is a good option, offering a free tier for up to 10,000 monthly active users. Additionally, I would like to know what type of user data needs to be stored, aside from search history. Thanks!

**Comment by JustinhSE** [comment]
@unclebinary1001 thanks for starting the discussion. I was wondering what are the capabilities of clerk? I have heard of it used for Google auth, but compared to databases like Mongo or firebase, what does it provide?

**Comment by JustinhSE** [comment]
But to answer your question, basics like first name, last name, userID. Login should be a primary usage for the database using Google or email + pwd. I would also like to add GitHub login option but that's only preferred. But the vision is to have a basic database that admin can use so that let's say one day we integrate some messaging tool, we can add fields as needed when making new features.

**Comment by VarunChopra11** [comment]
Please assign the above issue to me, I like to work on it using google oauth and github oauth if required. 
And also please provide a detailed description of the requirements.
We can connect over discord for further discussions, here is my username: varunchopra11 .

**Comment by JustinhSE** [comment]
Just messaged you on discord @VarunChopra11
