### ISSUE TITLE
Machine Learning/Web Development - Gemini ChatBot

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#4]
### Overview 🏗️ 

We are looking to add a Gemini chatbot to our platform, either as a popup or on its own page separate from the main one. The chatbot will be powered by Gemini AI and we want to ensure that it only sources information from biblical sources. To achieve this, we plan to integrate RAG (Retrieval Augmented Generation) into the chatbot. The chatbot should be designed to ignore questions that do not relate to the Bible.

### Task 🔧 

- Integrate Gemini chatbot into the platform.
- Set up the chatbot to either appear as a popup or on its own separate page.
- Configure the chatbot to source information only from biblical sources.
- Implement RAG to ensure that the chatbot adheres to biblical sources.
- Prompt engineer the chatbot to ignore questions not relating to the Bible.

**Comment by amannaik247** [comment]
Hey, I would be glad to work on this issue. My plan is to integrate this chatbot using Gemini API as you said, along with Qdrant or Mongodb for vector database . Can we connect on discord to discuss this a little before I start working on it ?

**Comment by JustinhSE** [comment]
@amannaik247 yeah for sure! We can definitely discuss. I am glad you brought up mongodb as our database too, as we are trying to establish a DB in #3

**Comment by JustinhSE** [comment]
@Namit2111 do you mind working with him on this on what your ideas were in executing this concerning the RAG portion?

**Comment by Namit2111** [comment]
Hey @amannaik247  We want only API for this right, we will be making a seprate page for this in future after the issue #2  is closed. So, for now only an api in flask is required. Can you guide me through the steps you will be taking along with tech stack

**Comment by amannaik247** [comment]
So I will be using Gemini Embeddings to embedd the bible's data and store it in a vector store, preferrably mongodb atlas, but for the chatbot response I recommend using Groq's llama model which work great and is free to use. I am not much used to flask api so might need your help with that.

**Comment by Sony-MetaShot** [comment]
Hey can I also work on this?

**Comment by JustinhSE** [comment]
@Sony-MetaShot this issue is actually under development currently. We want to find the best database to integrate

**Comment by JustinhSE** [comment]
@Namit2111 what would you like me to do with this issue?

**Comment by Namit2111** [comment]
@JustinhSE you can close this one too , as basic implementation is done , now just need to convert in an api ,I opened another issue for that
