### ISSUE TITLE
HTML - Center Title

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#6]
![image](https://github.com/user-attachments/assets/a1de3877-114f-457e-8712-16f2ef236d4c)

The title is not centered, help us center it! 

Bonus: Enhance the text font

**Comment by lisamessier** [comment]
https://github.com/Namit2111/bible-verse-finder/pull/9

**Comment by JustinhSE** [comment]
PR from @lisamessier
