### ISSUE TITLE
API Integration - Multiple Bible Translations 

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#7]
Overview:
We need to integrate multiple Bible translations into our application. Currently, we only have the KJV version available. To enhance user experience, we need the following feature:
- Multiple Translations: Allow users to compare verses across different Bible translations.

Tasks:
1. Research and Identify API: Find an API that provides access to multiple Bible translations and supports the features mentioned above.
2. Integration: Integrate the selected API into our application to enable the display of different Bible translations 
3. Add a button next to the results to convert the scriptures into the user's selected version.

**Comment by fortune710** [comment]
Hey @JustinhSE @Namit2111 I'd love to contribute to this repository. Can I take on this issue?

**Comment by JustinhSE** [comment]
@fortune710 yes! Pleae check `CONTRIBUTING.md` before working on this issue

**Comment by JustinhSE** [comment]
@fortune710 check this out https://bible-api.com/.  It is straightforward in its use but let me know if you find any others. The objective would be to select available translations with a button and have the output come from the API (some particular verse) in that translation

**Comment by fortune710** [comment]
sure i will check it out and let you know my thoughts!

**Comment by sukuasoft** [comment]
@JustinhSE Can I work on this issue?

**Comment by JustinhSE** [comment]
@sukuasoft you are open to coauthoring with @fortune710 if he is fine with it

**Comment by fortune710** [comment]
i'm fine with it

**Comment by fortune710** [comment]
hey @JustinhSE @Namit2111. I tried cloning and it gave me this error:
error: invalid path '.github/PULL_REQUEST_TEMPLATE.md '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

which leads to my question, wouldn't it be better to have the `.github/PULL_REQUEST_TEMPLATE.md` file in the root of the project along with `CONTRIBUTING.md`

**Comment by JustinhSE** [comment]
@fortune710 let me look

**Comment by JustinhSE** [comment]
@fortune710 have you forked the repo first? And then created a clone within your fork?

**Comment by fortune710** [comment]
yes i have, i was attempting to clone my fork

**Comment by JustinhSE** [comment]
@fortune710 havw you tried again?

**Comment by fortune710** [comment]
@JustinhSE yes i have, it works now. thank you very much

**Comment by JustinhSE** [comment]
@fortune710 great! Any updates yet?

**Comment by fortune710** [comment]
yes there is an update! i've been able to call the API as expected but is it fine if i install a third party library to help with caching API responses? (the library is `@tanstack/react-query`)

**Comment by Namit2111** [comment]
Yes go ahead @fortune710

**Comment by fortune710** [comment]
alright then!

**Comment by fortune710** [comment]
@JustinhSE @Namit2111 I just created a Pull Request for this issue!

**Comment by JustinhSE** [comment]
@fortune710 by the way next time add the issue # that your pr closes. Also whenever you are ready to open a pr, just open it so I can review it

**Comment by fortune710** [comment]
@JustinhSE Ohh, I actually did add that though, under the Related Issues section in the PR description, or is there a way I should've written it?

**Comment by JustinhSE** [comment]
@fortune710 just a reminder to start a PR in the next days to be eligible for the end of hacktoberfest

**Comment by JustinhSE** [comment]
@fortune710 any updates?
