### ISSUE TITLE
Bug : Frontend is not displaying response 

### ISSUE THREAD

**Issue by ByteJoseph** [Namit2111/bible-verse-finder#70]
# Here is the video showing the bug and the API response check.

https://github.com/user-attachments/assets/46db3ebc-bc49-4788-b0af-b8baeb55fb6b

**Comment by JustinhSE** [comment]
Hey @ByteJoseph it is a bug I am currently trying to fix. We transitioned yesterday not only in our vectorization  methods (tf-idf to hugging face transformers) but also our retrieval methods (Gutenberg -> json)

**Comment by JustinhSE** [comment]
It is in the backend the issue, most likely in utils.py. I need to see what exactly is causing the issue as it worked on my local host

**Comment by ByteJoseph** [comment]
> It is in the backend the issue, most likely in utils.py. I need to see what exactly is causing the issue as it worked on my local host

Good @JustinhSE , I am also trying to find it.

**Comment by ByteJoseph** [comment]
@JustinhSE Please review this commit #44

**Comment by JustinhSE** [comment]
Yes in that iteration it works fine @ByteJoseph

**Comment by JustinhSE** [comment]
It is due to either memory usage errors or syntax. Not at my laptop but can you see if it works locally? @ByteJoseph

**Comment by ByteJoseph** [comment]
> It is due to either memory usage errors or syntax. Not at my laptop but can you see if it works locally? @ByteJoseph

I am far from home, and I don’t have a PC right now. I will try to debug the frontend using the Termux app.

**Comment by JustinhSE** [comment]
Figured out that @Namit2111 needs to deploy the back end
