### ISSUE TITLE
Add an .env.sample file for the frontend

### ISSUE THREAD

**Issue by Agastya18** [Namit2111/bible-verse-finder#77]
To improve developer experience and streamline setup, I suggest adding an .env.sample file to the frontend directory. This file should include placeholder keys for all required environment variables, along with comments or example values if possible.

Adding an .env.sample file will:

Help new contributors set up their environment quickly.
Ensure clarity about the required environment variables for the project.

**Comment by JustinhSE** [comment]
thanks for the suggestion. This was on the backlog as some API key's are needed for developing features.

**Comment by JustinhSE** [comment]
After finals this is something I will be looking at
